version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ChangeMe
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@itmo.ru
      PGADMIN_DEFAULT_PASSWORD: ChangeMe
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
